REFACTOR

diff --git a/templates/default/haproxy-init.erb b/templates/default/haproxy-init.erb
--- a/templates/default/haproxy-init.erb
+++ b/templates/default/haproxy-init.erb
@@ -1,165 +1,109 @@
 #!/bin/sh
-### BEGIN INIT INFO
-# Provides:          haproxy
-# Required-Start:    $local_fs $network $remote_fs
-# Required-Stop:     $local_fs $remote_fs
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: fast and reliable load balancing reverse proxy
-# Description:       This file should be used to start and stop haproxy.
-### END INIT INFO
+#
+# haproxy
+#
+# chkconfig:   - 85 15
+# description:  HAProxy is a free, very fast and reliable solution \
+#               offering high availability, load balancing, and \
+#               proxying for TCP and  HTTP-based applications
+# processname: haproxy
+# config:      /etc/haproxy/haproxy.cfg
+# pidfile:     /var/run/haproxy.pid
 
-# Author: Arnaud Cornet <acornet@debian.org>
+# Source function library.
+. /etc/rc.d/init.d/functions
 
-# Written by Chef on <%= @hostname %>
+# Source networking configuration.
+. /etc/sysconfig/network
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-PIDFILE=/var/run/haproxy.pid
-CONFIG=<%= @conf_dir %>/haproxy.cfg
-HAPROXY=<%= @prefix %>/sbin/haproxy
-EXTRAOPTS=
-ENABLED=0
+# Check that networking is up.
+[ "$NETWORKING" = "no" ] && exit 0
 
-test -x $HAPROXY || exit 0
-test -f "$CONFIG" || exit 0
+exec="/usr/sbin/haproxy"
+prog=$(basename $exec)
 
-if [ -e /etc/default/haproxy ]; then
-  . /etc/default/haproxy
-fi
+[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
 
-test "$ENABLED" != "0" || exit 0
+lockfile=/var/lock/subsys/haproxy
 
-[ -f /etc/default/rcS ] && . /etc/default/rcS
-. /lib/lsb/init-functions
-
-
-haproxy_start()
-{
-  start-stop-daemon --start --pidfile "$PIDFILE" \
-    --exec $HAPROXY -- -f "$CONFIG" -D -p "$PIDFILE" \
-    $EXTRAOPTS || return 2
-  return 0
+check() {
+    $exec -c -V -f /etc/$prog/$prog.cfg
 }
 
-haproxy_stop()
-{
-  if [ ! -f $PIDFILE ] ; then
-    # This is a success according to LSB
-    return 0
-  fi
-  for pid in $(cat $PIDFILE) ; do
-    /bin/kill $pid || return 4
-  done
-  rm -f $PIDFILE
-  return 0
-}
-
-haproxy_reload()
-{
-  $HAPROXY -f "$CONFIG" -p $PIDFILE -D $EXTRAOPTS -sf $(cat $PIDFILE) \
-    || return 2
-  return 0
-}
-
-haproxy_status()
-{
-  if [ ! -f $PIDFILE ] ; then
-    # program not running
-    return 3
-  fi
-
-  for pid in $(cat $PIDFILE) ; do
-    if ! ps --no-headers p "$pid" | grep haproxy > /dev/null ; then
-      # program running, bogus pidfile
-      return 1
+start() {
+    $exec -c -q -f /etc/$prog/$prog.cfg
+    if [ $? -ne 0 ]; then
+        echo "Errors in configuration file, check with $prog check."
+        return 1
     fi
-  done
 
-  return 0
+    echo -n $"Starting $prog: "
+    # start it up here, usually something like "daemon $exec"
+    daemon $exec -D -f /etc/$prog/$prog.cfg -p /var/run/$prog.pid
+    retval=$?
+    echo
+    [ $retval -eq 0 ] && touch $lockfile
+    return $retval
 }
 
+stop() {
+    echo -n $"Stopping $prog: "
+    # stop it here, often "killproc $prog"
+    kill `pidof $prog`
+    retval=$?
+    echo
+    [ $retval -eq 0 ] && rm -f $lockfile
+    return $retval
+}
+
+restart() {
+    $exec -c -q -f /etc/$prog/$prog.cfg
+    if [ $? -ne 0 ]; then
+        echo "Errors in configuration file, check with $prog check."
+        return 1
+    fi
+    stop
+    start
+}
+
+reload() {
+    $exec -c -q -f /etc/$prog/$prog.cfg
+    if [ $? -ne 0 ]; then
+        echo "Errors in configuration file, check with $prog check."
+        return 1
+    fi
+    echo -n $"Reloading $prog: "
+    $exec -D -f /etc/$prog/$prog.cfg -p /var/run/$prog.pid -sf $(cat /var/run/$prog.pid)
+    retval=$?
+    echo
+    return $retval
+}
+
+force_reload() {
+    restart
+}
+
+fdr_status() {
+    status $prog
+}
 
 case "$1" in
-start)
-  log_daemon_msg "Starting haproxy" "haproxy"
-  haproxy_start
-  ret=$?
-  case "$ret" in
-  0)
-    log_end_msg 0
-    ;;
-  1)
-    log_end_msg 1
-    echo "pid file '$PIDFILE' found, haproxy not started."
-    ;;
-  2)
-    log_end_msg 1
-    ;;
-  esac
-  exit $ret
-  ;;
-stop)
-  log_daemon_msg "Stopping haproxy" "haproxy"
-  haproxy_stop
-  ret=$?
-  case "$ret" in
-  0|1)
-    log_end_msg 0
-    ;;
-  2)
-    log_end_msg 1
-    ;;
-  esac
-  exit $ret
-  ;;
-reload|force-reload)
-  log_daemon_msg "Reloading haproxy" "haproxy"
-  haproxy_reload
-  case "$?" in
-  0|1)
-    log_end_msg 0
-    ;;
-  2)
-    log_end_msg 1
-    ;;
-  esac
-  ;;
-restart)
-  log_daemon_msg "Restarting haproxy" "haproxy"
-  haproxy_stop
-  haproxy_start
-  case "$?" in
-  0)
-    log_end_msg 0
-    ;;
-  1)
-    log_end_msg 1
-    ;;
-  2)
-    log_end_msg 1
-    ;;
-  esac
-  ;;
-status)
-  haproxy_status
-  ret=$?
-  case "$ret" in
-  0)
-    echo "haproxy is running."
-    ;;
-  1)
-    echo "haproxy dead, but $PIDFILE exists."
-    ;;
-  *)
-    echo "haproxy not running."
-    ;;
-  esac
-  exit $ret
-  ;;
-*)
-  echo "Usage: /etc/init.d/haproxy {start|stop|reload|restart|status}"
-  exit 2
-  ;;
+    start|stop|restart|reload)
+        $1
+        ;;
+    force-reload)
+        force_reload
+        ;;
+    check)
+        check
+        ;;
+    status)
+        fdr_status
+        ;;
+    condrestart|try-restart)
+  	[ ! -f $lockfile ] || restart
+	;;
+    *)
+        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
+        exit 2
 esac
-
-:
